<h1> Differential Evolution (DE) </h1>

DE is a population-based optimization algorithm for continuous optimization problems.

**Core idea:**

DE utilizes the difference between solutions to navigate the search space.

In other words:

The distance and direction of movement between individuals in the population generate search information.

DE Core: Mutation Strategy

*DE/rand/1*

Formula:

$V_i=X_{r1}+F(X_{r2}-X_{r3})$

Parameter $F$ is the Differential Weight.

Key DE Parameters

Three main parameters:

1) F — Differential Weight </br>
The extent to which the difference between individuals is utilized.

Typically:</br>
$0.4 \leq F \leq 1$

1. If F is high:</br>
Larger movement</br>
Result:</br>
Greater exploration</br>
Higher probability of traversing/escaping regions</br>
But:</br>
Greater instability

2. If F is low:</br>
Small movement</br>
Result:</br>
Faster convergence</br>
Less exploration


2) CR — Crossover Rate

After mutation, a decision must be made:</br>
How much of the new vector is incorporated into the original solution.

1. Target Vector</br>
2. Donor (Mutant) Vector</br>
3. Trial Vector


3) Population Size

Like GA Larger population:</br>
1. Greater diversity</br>
2. Higher computational cost</br>
3. General DE Structure

For each individual Xi:</br>
1) Select Xr1, Xr2, Xr3</br>
2) Create Mutant Vector</br>
3) Crossover with Xi</br>
4) Create Trial Vector</br>
5) Compare Trial vs Xi</br>
6) Keep better one

One important difference from GA:

In GA:</br>
After generating the new generation:</br>
We had Elites + Offspring.

But in DE:</br>
Each individual competes against its own offspring: </br>

$Trial_i \quad vs \quad X_i$

If better:</br>
It replaces the original.

In other words, DE employs a type of greedy evolutionary replacement.

Unlike the GA we used for the Knapsack problem, DE is suitable for continuous optimization problems.

In [8]:
import numpy as np

from problems.benchmark_functions import sphere_function
from src.DE import (
    initialize_population,
    mutation,
    boundary_handling,
    mutation_with_boundary,
    crossover,
)

<h3> Step 1: Sphere Function </h3>

$F(x)=∑_(i=1) nx_i^2 $

In [9]:
x = np.array(
    [2, -3, 1]
)

sphere_function(x)

14

<h3> Step 2: Initial Population </h3>

In [10]:
population = initialize_population(
    population_size=5,
    dimension=2,
    bounds=[
        (-5,5),
        (-5,5)
    ]
)

population

array([[-2.88687321, -0.67853891],
       [ 3.62587723, -3.17038274],
       [ 1.6834124 , -1.23775647],
       [ 1.83592829, -2.01525752],
       [-3.24579391, -4.45097056]])

<h3> Step 3: Mutation (DE/rand/1) </h3>

This section is the heart of Differential Evolution.

In GA, mutation was a random change to the genes.

However, in DE, mutation is completely different. </br>
DE utilizes the distance and direction of movement between individuals in the population.

In [11]:
population = np.array(
    [
        [5,2],
        [3,1],
        [1,4],
        [2,5],
        [-1,3],
    ]
)

mutant = mutation(
    population,
    target_index=0,
    F=0.5,
)

print(mutant)

[-1.  5.]


<h3> Step 4: Boundary Handling </h3>

Methods:

1. Clipping
2. Reflection
3. Random Reinitialization

In [12]:
vector = np.array(
    [
        8,
        -12,
        3
    ]
)

bounds = [
    (-5,5),
    (-10,10),
    (-2,2),
]

boundary_handling(
    vector,
    bounds,
)

array([  5, -10,   2])

An important conceptual point:

In GA:

Mutation itself was the driver of change.

However, in DE:

Mutation:

Acts as the driver of directed movement within the solution space.

Therefore, boundary handling is more critical in DE, as the movements involved can be large.

In [13]:
mutant = mutation_with_boundary(
    population,
    target_index=0,
    F=0.8,
    bounds=[
        (-5,5),
        (-5,5)
    ],
)

print(mutant)

[4.6 1.8]


<h3> Step 5: Crossover (Binomial Crossover) </h3>

In [14]:
target = np.array(
    [1,2,3,4]
)

mutant = np.array(
    [9,8,7,6]
)

trial = crossover(
    target,
    mutant,
    CR=0.5,
)

print(trial)

[9 8 7 4]
